### ISSUE TITLE
CUDNN failure: CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by OuHangKresnik** [jiazhihao/TASO#11]
Failure in measure_element_cost cudnnOpTensor

Since couldn't get the name of this op, just hard to debug. Hope we can add such information in taso  OpBase class or somewhere else suitable

**Comment by jiazhihao** [comment]
More debug information are added for Element-wise operators as of commit 86e00198. To information more gdb information, you can rebuild the TASO runtime in debug mode using the following steps:
`rm -rf build; mkdir build; cd build`
`cmake -DCMAKE_BUILD_TYPE=Debug ..`
`sudo make install -j`

**Comment by OuHangKresnik** [comment]
It doesn't showed up, close this issue for now
