### ISSUE TITLE
Possible unsupported operators

### ISSUE THREAD

**Issue by OuHangKresnik** [jiazhihao/TASO#15]
Here is the list of possible unsupported operators besides StridedSlice:

NonMaxSuppressionV2
Fill
CropAndResize
TopKV2 
ResizeNearestNeighbor,
Merge

I see there is TopK in onnx while don't know what's the difference yet, investigating now.
For this operator plz see: https://github.com/onnx/tensorflow-onnx/issues/715
That's why I convert it as custom operator instead of the official conversion.
So does ResizesNearestNeighbor, Fill

**Comment by OuHangKresnik** [comment]
How about pay attention to NonMaxSuppressionV2, Merge and CropAndResize first.
I will continue to investigate TopKV2, ResizesNearestNeighbor and Fill

**Comment by OuHangKresnik** [comment]
TopKV2 , ResizesNearestNeighbor and Fill can be successfully transformed to onnx operators if upgraded the opset. So does the StridedSlice

**Comment by interesaaat** [comment]
I would also add gather if possible.
