### ISSUE TITLE
CPU/GPU

### ISSUE THREAD

**Issue by sonfire186** [jiazhihao/TASO#16]
If I perform optimization on a computer without a GPU and I will run it on a GPU. 
Will it affect performance?

**Comment by jiazhihao** [comment]
@sonfiree Thanks for your interests in TASO.

TASO optimize DNN computation graphs based on the runtime measurements of different DNN operators on the actual hardware backend. Therefore, we recommend to run TASO on the GPU backend you are optimizing for.

**Comment by sonfire186** [comment]
And how should I be in production?
For example, I use a 1080 card, and in production I already have two 2080.
It turns out in the power is distinguishing. On a machine in production, I cannot run the code.

**Comment by jiazhihao** [comment]
@sonfiree TASO may use different graph optimizations for different GPU backends. So you should run TASO on the production GPU. Can you briefly explain the error message you got on 2080?

**Comment by sonfire186** [comment]
I have not received anything. I just started testing.
I wanted to know how to better deploy the graph and tests.
