### ISSUE TITLE
assert num == 0 in split

### ISSUE THREAD

**Issue by OuHangKresnik** [jiazhihao/TASO#23]
In split.cc:137  parent.divide(left, right, curPos); the assertion is broken.

I have a temp fix to make:

  SplitInfo parent = inputs[0].split[axis], left, right;
  parent.num = inputs[0].dim[axis];

But the overall logic should also be checked as well in initialization of tensor.split field

**Comment by jiazhihao** [comment]
This should be fixed by commit 68b24d346.
