### ISSUE TITLE
python test from docker image not working

### ISSUE THREAD

**Issue by interesaaat** [jiazhihao/TASO#5]
Hi, I pulled the docker image. The programs in the example folder run nicely. However if I try to run TASO on an ONNX model, for example by calling `python python/test.py` I get 

```
Traceback (most recent call last):
  File "python/test.py", line 1, in <module>
    import taso
  File "/usr/TASO/python/taso/__init__.py", line 1, in <module>
    from .core import *
ModuleNotFoundError: No module named 'taso.core'
```

I tried to recompile the project but I am still getting the same error.

**Comment by jiazhihao** [comment]
Thanks for trying TASO. The error is because there is a folder called `taso` in `/usr/TASO/python'. So when you run `test.py`, python will look for modules inside the taso folder. An easy way to fix this is to move `test.py` to a different folder. I have updated this in the source code and docker.

**Comment by interesaaat** [comment]
Thanks for the quick update! I saw that you moved the ONNX test into example. I tried and now I get the following:

```
Traceback (most recent call last):
  File "onnx_test.py", line 4, in <module>
    old_model = taso.load_onnx("airline.onnx")
AttributeError: module 'taso' has no attribute 'load_onnx'
```

**Comment by jiazhihao** [comment]
Thanks for reporting error --- this is due to a name mismatch between our document and the Python API. I have fixed the naming issue, and you now should be able to use `load_onnx` to load an ONNX file.

You will need to reinstall the TASO Python frontend by running `python setup.py install`

**Comment by interesaaat** [comment]
Thanks it worked! I have another problem now, I will fill another issue.

**Comment by rycolab** [comment]
I don't believe this was fixed in the docker image yet! I run into the same issue when trying to use the python shell from the docker image

**Comment by vinayak618** [comment]
Hi @jiazhihao ,

I successfully installed taso from source, when i run it to verify with command "import taso"
It throws the below error:

taso/__init__.py", line 1, in <module>
    from .core import *
ModuleNotFoundError: No module named 'taso.core'.

Any help here?

Thanks,

Vinayak

**Comment by jiazhihao** [comment]
@vinayak618 It seems you may not have Cython installed --- it currently returns a warning instead of a error when you install the TASO python package. Can you please verify that you have Cython?

**Comment by vinayak618** [comment]
Hi @jiazhihao ,

Checked with cython, it's installed and the version is 0.29.14
`pip install cython`
 `Requirement already satisfied: cython in /home/ubuntu/anaconda3/lib/python3.7/site-packages (0.29.14)`

Error: 
`/taso/__init__.py", line 1, in <module>
    from .core import *
ModuleNotFoundError: No module named 'taso.core'
`

**Comment by puddingfjz** [comment]
Hi  @jiazhihao ,
I am using the docker image, 
I generate alexnet.onnx by
```
from torch.autograd import Variable
import torch.onnx
import torchvision

dummy_input = Variable(torch.randn(10, 3, 224, 224)).cuda()
model = torchvision.models.alexnet(pretrained=True).cuda()

input_names = [ "actual_input_1" ] + [ "learned_%d" % i for i in range(16) ]
output_names = [ "output1" ]

torch.onnx.export(model, dummy_input, "alexnet.onnx", verbose=True, input_names=input_names, output_names=output_names)
```

Then I run 
```
model2 = taso.load_onnx("alexnet.onnx")
```
the following error appears:
```
>>> model2 = taso.load_onnx("alexnet.onnx")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/taso-0.1.0-py3.7-linux-x86_64.egg/taso/__init__.py", line 730, in load_onnx
    assert len(node_list) == len(model.graph.node), "Internal error when reording ONNX operators"
AssertionError: Internal error when reording ONNX operators
```
