### ISSUE TITLE
Why "generator" building is not a part of CMakeLists.txt?

### ISSUE THREAD

**Issue by burlachenkok** [jiazhihao/TASO#53]
Dear TASO authors. There are no conditional statements inside the project file:
https://github.com/jiazhihao/TASO/blob/master/CMakeLists.txt

I have observed that I can build "generator.cc" via https://github.com/jiazhihao/TASO/blob/master/src/generator/compile.sh

But why is it not a part of CMakeLists.txt ? 
Is it due to historical reasons or it's so just due to some hidden problem?

**Comment by jiazhihao** [comment]
@burlachenkok Thank you for your interests in TASO. This is because we expect that most users would like to directly use pre-generated graph substitutions without having to rerun the TASO generator. You can always build and run the generator using the compile.sh file you discovered.

**Comment by burlachenkok** [comment]
Thanks
