### ISSUE TITLE
A bug about transpose???

### ISSUE THREAD

**Issue by StepyHan** [jiazhihao/TASO#63]
https://github.com/jiazhihao/TASO/blob/master/src/core/transpose.cc#L60
Hi dear author, it seems that the " != " should be modified to "==" : )
```
  for (int i = 0; i < ndim; i++)
    for (int j = i + 1; j < ndim; j++)
      if (permArray[i] != permArray[j]) {
        return Op::INVALID_OP;
      }
```

**Comment by jiazhihao** [comment]
Thanks for the report. The bug should have been fixed.
